//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuarDatabaseEntities : DbContext
    {
        public FuarDatabaseEntities()
            : base("name=FuarDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EgitimTablo> EgitimTablo { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<SemtMah> SemtMah { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Amac> tbl_Amac { get; set; }
        public virtual DbSet<tbl_BasinFirma> tbl_BasinFirma { get; set; }
        public virtual DbSet<tbl_BasinFirmaCalisanlar> tbl_BasinFirmaCalisanlar { get; set; }
        public virtual DbSet<tbl_BasinKatildigiFuarlar> tbl_BasinKatildigiFuarlar { get; set; }
        public virtual DbSet<tbl_Departman> tbl_Departman { get; set; }
        public virtual DbSet<tbl_FaaliyetTuru> tbl_FaaliyetTuru { get; set; }
        public virtual DbSet<tbl_FaatliyetAlani> tbl_FaatliyetAlani { get; set; }
        public virtual DbSet<tbl_Fuar> tbl_Fuar { get; set; }
        public virtual DbSet<tbl_FuarBasinBulteni> tbl_FuarBasinBulteni { get; set; }
        public virtual DbSet<tbl_FuarKapsamAlani> tbl_FuarKapsamAlani { get; set; }
        public virtual DbSet<tbl_FuarKapsamTuru> tbl_FuarKapsamTuru { get; set; }
        public virtual DbSet<tbl_FuarKatilimciProfil> tbl_FuarKatilimciProfil { get; set; }
        public virtual DbSet<tbl_FuarResimler> tbl_FuarResimler { get; set; }
        public virtual DbSet<tbl_FuarZiyaretciProfil> tbl_FuarZiyaretciProfil { get; set; }
        public virtual DbSet<tbl_KatilimciFaaliyetAlani> tbl_KatilimciFaaliyetAlani { get; set; }
        public virtual DbSet<tbl_KatilimciFaaliyetTuru> tbl_KatilimciFaaliyetTuru { get; set; }
        public virtual DbSet<tbl_KatilimciFirma> tbl_KatilimciFirma { get; set; }
        public virtual DbSet<tbl_KatilimciFirmaCalisanlar> tbl_KatilimciFirmaCalisanlar { get; set; }
        public virtual DbSet<tbl_KatilimciKatildigiFuarlar> tbl_KatilimciKatildigiFuarlar { get; set; }
        public virtual DbSet<tbl_KatilimciKatilimAmac> tbl_KatilimciKatilimAmac { get; set; }
        public virtual DbSet<tbl_KatilimciProfil> tbl_KatilimciProfil { get; set; }
        public virtual DbSet<tbl_Kisiler> tbl_Kisiler { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_OrganizatorFaaliyetAlani> tbl_OrganizatorFaaliyetAlani { get; set; }
        public virtual DbSet<tbl_OrganizatorFaaliyetTuru> tbl_OrganizatorFaaliyetTuru { get; set; }
        public virtual DbSet<tbl_OrganizatorFirma> tbl_OrganizatorFirma { get; set; }
        public virtual DbSet<tbl_OrganizatorFirmaCalisanlar> tbl_OrganizatorFirmaCalisanlar { get; set; }
        public virtual DbSet<tbl_OrganizatorKatildigiFuarlar> tbl_OrganizatorKatildigiFuarlar { get; set; }
        public virtual DbSet<tbl_Pozisyon> tbl_Pozisyon { get; set; }
        public virtual DbSet<tbl_UrunGruplari> tbl_UrunGruplari { get; set; }
        public virtual DbSet<tbl_ZiyaretciFaaliyetAlani> tbl_ZiyaretciFaaliyetAlani { get; set; }
        public virtual DbSet<tbl_ZiyaretciFaaliyetTuru> tbl_ZiyaretciFaaliyetTuru { get; set; }
        public virtual DbSet<tbl_ZiyaretciFirma> tbl_ZiyaretciFirma { get; set; }
        public virtual DbSet<tbl_ZiyaretciFirmaCalisanlar> tbl_ZiyaretciFirmaCalisanlar { get; set; }
        public virtual DbSet<tbl_ZiyaretciIlgilendigiUrun> tbl_ZiyaretciIlgilendigiUrun { get; set; }
        public virtual DbSet<tbl_ZiyaretciKatildigiFuarlar> tbl_ZiyaretciKatildigiFuarlar { get; set; }
        public virtual DbSet<tbl_ZiyaretciKatilimAmaci> tbl_ZiyaretciKatilimAmaci { get; set; }
        public virtual DbSet<tbl_ZiyaretciProfil> tbl_ZiyaretciProfil { get; set; }
        public virtual DbSet<TestTablo> TestTablo { get; set; }
    }
}
