//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UrunGruplari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UrunGruplari()
        {
            this.tbl_ZiyaretciIlgilendigiUrun = new HashSet<tbl_ZiyaretciIlgilendigiUrun>();
        }
    
        public int urunId { get; set; }
        public string urunGrupAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciIlgilendigiUrun> tbl_ZiyaretciIlgilendigiUrun { get; set; }
    }
}
