//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KatilimciProfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KatilimciProfil()
        {
            this.tbl_FuarKatilimciProfil = new HashSet<tbl_FuarKatilimciProfil>();
        }
    
        public int kProfilId { get; set; }
        public string kProfilAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarKatilimciProfil> tbl_FuarKatilimciProfil { get; set; }
    }
}
