//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BasinFirma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BasinFirma()
        {
            this.tbl_BasinFirmaCalisanlar = new HashSet<tbl_BasinFirmaCalisanlar>();
            this.tbl_BasinKatildigiFuarlar = new HashSet<tbl_BasinKatildigiFuarlar>();
        }
    
        public int bId { get; set; }
        public string bFirmaAdi { get; set; }
        public string bWebSiteUrl { get; set; }
        public string bTelefon { get; set; }
        public string bFax { get; set; }
        public string bMail { get; set; }
        public string bResimUrl { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public string bOnay { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BasinFirmaCalisanlar> tbl_BasinFirmaCalisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BasinKatildigiFuarlar> tbl_BasinKatildigiFuarlar { get; set; }
    }
}
