//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZiyaretciIlgilendigiUrun
    {
        public int zIlgilendigiUrunId { get; set; }
        public int zId { get; set; }
        public int urunId { get; set; }
        public string diger { get; set; }
    
        public virtual tbl_UrunGruplari tbl_UrunGruplari { get; set; }
        public virtual tbl_ZiyaretciFirma tbl_ZiyaretciFirma { get; set; }
    }
}
