//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KatilimciFirma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KatilimciFirma()
        {
            this.tbl_KatilimciFaaliyetAlani = new HashSet<tbl_KatilimciFaaliyetAlani>();
            this.tbl_KatilimciFaaliyetTuru = new HashSet<tbl_KatilimciFaaliyetTuru>();
            this.tbl_KatilimciFirmaCalisanlar = new HashSet<tbl_KatilimciFirmaCalisanlar>();
            this.tbl_KatilimciKatildigiFuarlar = new HashSet<tbl_KatilimciKatildigiFuarlar>();
            this.tbl_KatilimciKatilimAmac = new HashSet<tbl_KatilimciKatilimAmac>();
        }
    
        public int kId { get; set; }
        public string kFirmaAdi { get; set; }
        public string kWebSiteUrl { get; set; }
        public string kTelefon { get; set; }
        public string kFax { get; set; }
        public string kMail { get; set; }
        public string kResimUrl { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public int kCalisanSayisi { get; set; }
        public string kOnay { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciFaaliyetAlani> tbl_KatilimciFaaliyetAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciFaaliyetTuru> tbl_KatilimciFaaliyetTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciFirmaCalisanlar> tbl_KatilimciFirmaCalisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciKatildigiFuarlar> tbl_KatilimciKatildigiFuarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciKatilimAmac> tbl_KatilimciKatilimAmac { get; set; }
    }
}
