//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kisiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kisiler()
        {
            this.tbl_BasinFirmaCalisanlar = new HashSet<tbl_BasinFirmaCalisanlar>();
            this.tbl_KatilimciFirmaCalisanlar = new HashSet<tbl_KatilimciFirmaCalisanlar>();
            this.tbl_OrganizatorFirmaCalisanlar = new HashSet<tbl_OrganizatorFirmaCalisanlar>();
            this.tbl_ZiyaretciFirmaCalisanlar = new HashSet<tbl_ZiyaretciFirmaCalisanlar>();
        }
    
        public int kisiId { get; set; }
        public string kisiIsim { get; set; }
        public string kisiSoyisim { get; set; }
        public string kisiTelefon { get; set; }
        public string kisiTcNo { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public string kisiMail { get; set; }
        public string kisiResimUrl { get; set; }
        public Nullable<int> departmanId { get; set; }
        public Nullable<int> pozisyonId { get; set; }
        public int kullaniciId { get; set; }
        public string kullaniciTuru { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BasinFirmaCalisanlar> tbl_BasinFirmaCalisanlar { get; set; }
        public virtual tbl_Departman tbl_Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciFirmaCalisanlar> tbl_KatilimciFirmaCalisanlar { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        public virtual tbl_Pozisyon tbl_Pozisyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorFirmaCalisanlar> tbl_OrganizatorFirmaCalisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciFirmaCalisanlar> tbl_ZiyaretciFirmaCalisanlar { get; set; }
    }
}
