//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FaatliyetAlani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FaatliyetAlani()
        {
            this.tbl_FuarKapsamAlani = new HashSet<tbl_FuarKapsamAlani>();
            this.tbl_KatilimciFaaliyetAlani = new HashSet<tbl_KatilimciFaaliyetAlani>();
            this.tbl_OrganizatorFaaliyetAlani = new HashSet<tbl_OrganizatorFaaliyetAlani>();
            this.tbl_ZiyaretciFaaliyetTuru = new HashSet<tbl_ZiyaretciFaaliyetTuru>();
        }
    
        public int faaliyetAlaniId { get; set; }
        public string faaliyetAlaniAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarKapsamAlani> tbl_FuarKapsamAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciFaaliyetAlani> tbl_KatilimciFaaliyetAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorFaaliyetAlani> tbl_OrganizatorFaaliyetAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciFaaliyetTuru> tbl_ZiyaretciFaaliyetTuru { get; set; }
    }
}
