//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KatilimciKatilimAmac
    {
        public int kKatilimAmacId { get; set; }
        public int kId { get; set; }
        public int amacId { get; set; }
        public string diger { get; set; }
    
        public virtual tbl_Amac tbl_Amac { get; set; }
        public virtual tbl_KatilimciFirma tbl_KatilimciFirma { get; set; }
    }
}
