//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrganizatorFirma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OrganizatorFirma()
        {
            this.tbl_OrganizatorFaaliyetAlani = new HashSet<tbl_OrganizatorFaaliyetAlani>();
            this.tbl_OrganizatorFaaliyetTuru = new HashSet<tbl_OrganizatorFaaliyetTuru>();
            this.tbl_OrganizatorFirmaCalisanlar = new HashSet<tbl_OrganizatorFirmaCalisanlar>();
            this.tbl_OrganizatorKatildigiFuarlar = new HashSet<tbl_OrganizatorKatildigiFuarlar>();
        }
    
        public int oId { get; set; }
        public string oFirmaAdi { get; set; }
        public string oWebSite { get; set; }
        public string oTelefon { get; set; }
        public string oFax { get; set; }
        public string oMail { get; set; }
        public string oResimUrl { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public Nullable<int> oCalisanSayisi { get; set; }
        public string oOnay { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorFaaliyetAlani> tbl_OrganizatorFaaliyetAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorFaaliyetTuru> tbl_OrganizatorFaaliyetTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorFirmaCalisanlar> tbl_OrganizatorFirmaCalisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorKatildigiFuarlar> tbl_OrganizatorKatildigiFuarlar { get; set; }
    }
}
