//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FuarKatilimciProfil
    {
        public int fKatilimId { get; set; }
        public int fuarId { get; set; }
        public int kProfilId { get; set; }
    
        public virtual tbl_Fuar tbl_Fuar { get; set; }
        public virtual tbl_KatilimciProfil tbl_KatilimciProfil { get; set; }
    }
}
