//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Amac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Amac()
        {
            this.tbl_KatilimciKatilimAmac = new HashSet<tbl_KatilimciKatilimAmac>();
            this.tbl_ZiyaretciKatilimAmaci = new HashSet<tbl_ZiyaretciKatilimAmaci>();
        }
    
        public int amacId { get; set; }
        public string amacAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciKatilimAmac> tbl_KatilimciKatilimAmac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciKatilimAmaci> tbl_ZiyaretciKatilimAmaci { get; set; }
    }
}
