//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZiyaretciFirma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ZiyaretciFirma()
        {
            this.tbl_ZiyaretciFaaliyetAlani = new HashSet<tbl_ZiyaretciFaaliyetAlani>();
            this.tbl_ZiyaretciFaaliyetTuru = new HashSet<tbl_ZiyaretciFaaliyetTuru>();
            this.tbl_ZiyaretciFirmaCalisanlar = new HashSet<tbl_ZiyaretciFirmaCalisanlar>();
            this.tbl_ZiyaretciIlgilendigiUrun = new HashSet<tbl_ZiyaretciIlgilendigiUrun>();
            this.tbl_ZiyaretciKatildigiFuarlar = new HashSet<tbl_ZiyaretciKatildigiFuarlar>();
            this.tbl_ZiyaretciKatilimAmaci = new HashSet<tbl_ZiyaretciKatilimAmaci>();
        }
    
        public int zId { get; set; }
        public string zFirmaAdi { get; set; }
        public string zWebSiteUrl { get; set; }
        public string zTelefon { get; set; }
        public string zFax { get; set; }
        public string zMail { get; set; }
        public string zResimUrl { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public int zCalisanSayisi { get; set; }
        public string zOnay { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciFaaliyetAlani> tbl_ZiyaretciFaaliyetAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciFaaliyetTuru> tbl_ZiyaretciFaaliyetTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciFirmaCalisanlar> tbl_ZiyaretciFirmaCalisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciIlgilendigiUrun> tbl_ZiyaretciIlgilendigiUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciKatildigiFuarlar> tbl_ZiyaretciKatildigiFuarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciKatilimAmaci> tbl_ZiyaretciKatilimAmaci { get; set; }
    }
}
