//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuar_Organizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fuar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Fuar()
        {
            this.tbl_BasinKatildigiFuarlar = new HashSet<tbl_BasinKatildigiFuarlar>();
            this.tbl_FuarBasinBulteni = new HashSet<tbl_FuarBasinBulteni>();
            this.tbl_FuarKapsamAlani = new HashSet<tbl_FuarKapsamAlani>();
            this.tbl_FuarKapsamTuru = new HashSet<tbl_FuarKapsamTuru>();
            this.tbl_FuarKatilimciProfil = new HashSet<tbl_FuarKatilimciProfil>();
            this.tbl_FuarResimler = new HashSet<tbl_FuarResimler>();
            this.tbl_FuarZiyaretciProfil = new HashSet<tbl_FuarZiyaretciProfil>();
            this.tbl_KatilimciKatildigiFuarlar = new HashSet<tbl_KatilimciKatildigiFuarlar>();
            this.tbl_OrganizatorKatildigiFuarlar = new HashSet<tbl_OrganizatorKatildigiFuarlar>();
            this.tbl_ZiyaretciKatildigiFuarlar = new HashSet<tbl_ZiyaretciKatildigiFuarlar>();
        }
    
        public int fuarId { get; set; }
        public string fuarAdi { get; set; }
        public int SehirId { get; set; }
        public int ilceId { get; set; }
        public int SemtMahId { get; set; }
        public string fuarTelNo { get; set; }
        public string fuarFax { get; set; }
        public System.DateTime fuarBaslamaTarih { get; set; }
        public System.DateTime fuarBitisTarih { get; set; }
        public string fuarFacebookUrl { get; set; }
        public string fuarInstagramUrl { get; set; }
        public string fuarTwitterUrl { get; set; }
        public string fuarOnay { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual SemtMah SemtMah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BasinKatildigiFuarlar> tbl_BasinKatildigiFuarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarBasinBulteni> tbl_FuarBasinBulteni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarKapsamAlani> tbl_FuarKapsamAlani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarKapsamTuru> tbl_FuarKapsamTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarKatilimciProfil> tbl_FuarKatilimciProfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarResimler> tbl_FuarResimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FuarZiyaretciProfil> tbl_FuarZiyaretciProfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KatilimciKatildigiFuarlar> tbl_KatilimciKatildigiFuarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizatorKatildigiFuarlar> tbl_OrganizatorKatildigiFuarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ZiyaretciKatildigiFuarlar> tbl_ZiyaretciKatildigiFuarlar { get; set; }
    }
}
